version: '3'
services:
  web_box:
    privileged: true
    container_name: web_box
    image: fanciestw/netsec:web_box
    build:
      context: .
      dockerfile: www.Dockerfile
    expose:
      - "80"
    networks:
      - private_net

  ssh_box:
    container_name: ssh_box
    image: fanciestw/netsec:ssh_box
    build:
      context: .
      dockerfile: ssh.Dockerfile
    expose:
      - "22"
    networks:
      - private_net
    privileged: true

  box3:
    container_name: box3
    image: fanciestw/netsec:box3
    build:
      context: .
      dockerfile: ssh.Dockerfile
    expose: 
      - "22"
    ports:
      - "8022:22"
    network_mode: bridge
    privileged: true

networks:
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.111.0/27